# Generated by Django 2.2.6 on 2019-11-02 12:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('RT', 'Recruiter'), ('SR', 'Job Seeker')], default='SR', max_length=2)),
                ('phone', models.CharField(max_length=20)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_salary', models.FloatField(blank=True)),
                ('is_annually', models.NullBooleanField()),
                ('currency', models.CharField(max_length=50)),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SeekerSkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.PositiveIntegerField()),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SkillSet')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_job', models.BooleanField(default=False, verbose_name='current Job?')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField()),
                ('job_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('job_location_city', models.CharField(max_length=50, verbose_name='city')),
                ('job_location_state', models.CharField(max_length=50, verbose_name='state')),
                ('job_location_country', models.CharField(max_length=50, verbose_name='country')),
                ('description', models.TextField()),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Seeker')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_degree_name', models.CharField(max_length=50, verbose_name='degree Name')),
                ('major', models.CharField(max_length=50)),
                ('institute_university_name', models.CharField(max_length=50, verbose_name='university/Institute Name')),
                ('starting_date', models.DateField(default=datetime.date.today)),
                ('completion_date', models.DateField(blank=True)),
                ('percentage', models.PositiveIntegerField(blank=True)),
                ('cgpa', models.FloatField(blank=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Seeker')),
            ],
        ),
    ]
