# Generated by Django 2.2.6 on 2019-11-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='currency',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
