# Generated by Django 2.2.6 on 2019-11-02 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('profile_description', models.TextField()),
                ('date_established', models.DateTimeField()),
                ('company_website_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_set_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=50, verbose_name='job Title')),
                ('is_company_name_hidden', models.BooleanField(default=False, verbose_name='hide Company Name?')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_description', models.TextField()),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('job_city', models.CharField(blank=True, max_length=50, verbose_name='city')),
                ('job_state', models.CharField(blank=True, max_length=50, verbose_name='state')),
                ('job_country', models.CharField(blank=True, max_length=50, verbose_name='country')),
                ('job_zip', models.CharField(blank=True, max_length=50, verbose_name='zip')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CompanyAccount')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostSkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.PositiveIntegerField()),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Post')),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SkillSet')),
            ],
        ),
        migrations.CreateModel(
            name='JobPostActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Post')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_image', models.ImageField(default='company.jpg', upload_to='profile_pics')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CompanyAccount')),
            ],
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='company_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CompanyType'),
        ),
    ]
