# Generated by Django 2.2.6 on 2019-11-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='notify_closed',
            field=models.BooleanField(default=True, verbose_name='Notify me when job is closed'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
